version: '3'
services:
    flask_api:
      build: flask_api/
      image: flask_api
      container_name: flask_api_container
      ports:
          - "5000:5000"
      environment:
        TZ: "Azia/Tokyo"
      volumes:
          - ./flask_api/app:/app/